---
kubernetes:
  children:
    master:
      hosts:
        k8s-control-0:
          ansible_host: 192.168.40.100
        k8s-control-1:
          ansible_host: 192.168.40.101
        k8s-control-2:
          ansible_host: 192.168.40.102
    worker:
      hosts:
        k8s-worker-3:
          ansible_host: 192.168.40.103
        k8s-worker-4:
          ansible_host: 192.168.40.104
        k8s-worker-5:
          ansible_host: 192.168.40.105
