---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Chicago
  METALLB_LB_RANGE: 192.168.40.110-192.168.40.120
  METALLB_K8S_GATEWAY_ADDR: 192.168.40.110
  METALLB_INGRESS_ADDR: 192.168.40.111
